apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: petch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: finaltest
  template:
    metadata: 
      name: myapp
      labels: 
        app: finaltest
    spec:
      containers:
        - name: myapp
          image: final:1.0.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata: 
  name: myapp-service
  namespace: petch
spec:
  type: NodePort
  selector: 
    app: finaltest
  ports:
    - port: 80 #defaultPort
      targetPort: 80
      nodePort: 30001
